services:
  itop:
    image: ghcr.io/cloudynes/php-itop:8.2-alpine
    container_name: itop
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - ./config:/app/config
  mysql:
    image: mariadb:10.11
    container_name: itop-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itop