version: "3.2"
services:
  php81-alpine-unit:
    image: ghcr.io/cloudynes/php-alpine-unit:8.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_VERSION: 8.1
    volumes:
      - ./config.json:/docker-entrypoint.d/config.json
    ports:
      - 8080:8080
