version: "3.2"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  php74:
    image: cloudyne.azurecr.io/php-bedrock:7.4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_VERSION: "7.4"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://wordpress:wordpress@mysql:3306/wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
      WP_ENV: development

  php80:
    image: cloudyne.azurecr.io/php-bedrock:8.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_VERSION: "8.0"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://wordpress:wordpress@mysql:3306/wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp

  php81:
    image: ghcr.io/cloudynes/php-bedrock:8.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_VERSION: "8.1"
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://wordpress:wordpress@mysql:3306/wordpress
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
  # php82:
  #   image: cloudyne.azurecr.io/php-bedrock:8.2
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql
  #   environment:
  #     environment:
  #     DATABASE_URL: mysql://wordpress:wordpress@mysql:3306/wordpress
  #     WP_HOME: http://localhost:8080
  #     WP_SITEURL: http://localhost:8080/wp