on:
    workflow_dispatch:
        inputs:
            image_name:
              type: string
              default: "php-bookstack:8.0-alpine"
              description: "The container image to build a debug version for"
            debug_packages:
              type: string
              default: "nano vim git zip"
              description: "The packages to install for debugging"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image ghcr.io/cloudynes/${{ github.event.inputs.image_name }}-debug
        uses: docker/build-push-action@v2
        with:
            context: ./alpine/debug-build
            file: ./alpine/debug-build/Dockerfile
            push: true
            build-args: |
              SOURCE_IMAGE=ghcr.io/cloudynes/${{ github.event.inputs.image_name }}
              DEBUG_PACKAGES=${{ github.event.inputs.debug_packages }}
            tags: |
                ghcr.io/cloudynes/${{ github.event.inputs.image_name }}-debug
