on:
    workflow_dispatch:
        inputs:
            container_base:
                type: choice
                default: "alpine"
                options:
                    - debian
                    - alpine
            
            container_image:
                type: choice
                options:
                    - php-extended
                    - php-unit
                    - php-bedrock
                    - php-laravel
                    - php-bookstack
            
            php_version:
                type: choice
                default: "8.0"
                options:
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
jobs:
    build:
        if: github.event.inputs.container_image != 'php-extended' && github.event.inputs.container_base != 'alpine'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          
          - name: Login to GHCR
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: cloudynes
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              registry: docker.io
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Login to Azure Container Registry
            uses: docker/login-action@v2
            with:
              registry: ${{ secrets.AZURECR_URL }}
              username: ${{ secrets.AZURECR_USER }}
              password: ${{ secrets.AZURECR_SECRET }}

          - name: Build and push ${{ github.events.inputs.container_image }}:${{ github.events.inputs.php_version }}-${{ github.events.inputs.container_base }}
            uses: docker/build-push-action@v2
            with:
                cache-from: type=registry,ref=ghcr.io/cloudynes/${{ github.events.inputs.container_image }}:cache-${{ github.events.inputs.php_version }}
                cache-to: type=registry,ref=ghcr.io/cloudynes/${{ github.events.inputs.container_image }}:cache-${{ github.events.inputs.php_version }}
                context: ./${{ github.events.inputs.container_base }}/${{ github.events.inputs.container_image }}
                file: ./${{ github.events.inputs.container_base }}/${{ github.events.inputs.container_image }}/Dockerfile
                push: true
                build-args: |
                    SOURCE_VERSION=${{ github.events.inputs.php_version }}
                tags: |
                    ghcr.io/cloudynes/${{ github.events.inputs.container_image }}:${{ github.events.inputs.php_version }}-${{ github.events.inputs.container_base }}
                    cloudyne/${{ github.events.inputs.container_image }}:${{ github.events.inputs.php_version }}-${{ github.events.inputs.container_base }}
                    cloudyne.azurecr.io/${{ github.events.inputs.container_image }}:${{ github.events.inputs.php_version }}-${{ github.events.inputs.container_base }}